POST http://localhost:9090/signup
	Content-Type: application/json
	# Email    string `json:"email" binding:"required"`
	# Password string `json:"password" binding:"required"`

	{
		"email": "test333@example.com",
		"password": "password"
	}