POST http://localhost:9090/events
Content-Type: application/json

	# ID          int       `json:"id"`
	# Title       string    `json:"title" binding:"required"`
	# Description string    `json:"description" binding:"required"`
	# Location    string    `json:"location" binding:"required"`
	# DateTime    time.Time `json:"date_time" binding:"required"`
	# UserID      int       `json:"userId"`

{
    "title": "Event 1",
    "description": "Event 1 Description",
    "location": "Event 1 Location",
    "date_time": "2021-07-01T00:00:00Z",
    "userId": 1
}
