POST http://localhost:9090/events
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA3NDMwMzY5LCJ1c2VySWQiOjJ9.fRGUlJMmxuRip1-P0npvMckBEH_8yTphwwv3bwvfhdc

	# Title       string    `json:"title" binding:"required"`
	# Description string    `json:"description" binding:"required"`
	# Location    string    `json:"location" binding:"required"`
	# DateTime    time.Time `json:"date_time" binding:"required"`
	# UserID      int       `json:"userId"`

{
    "title": "Event 5",
    "description": "Event 5 Description",
    "location": "Event 5 Location",
    "date_time": "5053-07-01T00:00:00Z"
}